local Plug = vim.fn["plug#"]
vim.call("plug#begin", "~/.config/nvim/plugged")

Plug("kyazdani42/nvim-web-devicons")
Plug("kyazdani42/nvim-tree.lua")
Plug("vim-airline/vim-airline")
Plug("vim-airline/vim-airline-themes")
Plug("ctrlpvim/ctrlp.vim")
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })
Plug("nvim-treesitter/playground")
Plug("EdenEast/nightfox.nvim")
Plug("neovim/nvim-lspconfig")
Plug("williamboman/nvim-lsp-installer")
Plug("nvim-lua/lsp-status.nvim")
Plug("nvim-lua/plenary.nvim")
Plug("nvim-telescope/telescope.nvim", { tag = "0.1.0" })
Plug("nvim-telescope/telescope-fzf-native.nvim", {
    ["do"] = "cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build",
})
Plug("hrsh7th/nvim-cmp")
Plug("saadparwaiz1/cmp_luasnip")
Plug("L3MON4D3/LuaSnip")
Plug("windwp/nvim-autopairs")
Plug("windwp/nvim-ts-autotag")
Plug("jose-elias-alvarez/null-ls.nvim")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("nvim-lua/popup.nvim")
Plug("jvgrootveld/telescope-zoxide")
Plug("bkad/CamelCaseMotion")
Plug("glepnir/lspsaga.nvim", { branch = "main" })

vim.call("plug#end")
